name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with sbt
        run: sbt compile

  unit_test:
    name:  unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run exception handling tests
        run: sbt "testOnly edu.cmu.cs.vbc.prog.ExceptionTest"

      - name: Run other small unit tests
        run: sbt "testOnly edu.cmu.cs.vbc.analysis.*Test edu.cmu.cs.vbc.utils.*Test edu.cmu.cs.vbc.vbytecode.*Test"

  example_small:
    name: test with small examples
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run BankAccount
        run: sbt "testOnly edu.cmu.cs.vbc.prog.BankAccountTest"

      - name: Run Elevator
        run: sbt "testOnly edu.cmu.cs.vbc.prog.ElevatorTest"

      - name: Run Email
        run: sbt "testOnly edu.cmu.cs.vbc.prog.EmailTest"

      - name: Run GPL
        run: sbt "testOnly edu.cmu.cs.vbc.prog.GPLTest"

      - name: Run small examples
        run: sbt "testOnly edu.cmu.cs.vbc.prog.SmallExampleTest"

  example_medium:
    name: test with medium examples
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Prevayler
        run: sbt "testOnly edu.cmu.cs.vbc.prog.PrevaylerTest"

      - name: Run QuEval
        run: sbt "testOnly edu.cmu.cs.vbc.prog.QuEvalTest"